/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AstroloqRouteImport } from './routes/astroloq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as HoroskopRouteImport } from './routes/horoskop'
import { Route as MetnuRouteImport } from './routes/metnu'
import { Route as QezetRouteImport } from './routes/qezet'
import { Route as UygunluqRouteImport } from './routes/uygunluq'
import { Route as AuthenticatedJurnalRouteImport } from './routes/_authenticated/jurnal'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedRezervasiyalarRouteImport } from './routes/_authenticated/rezervasiyalar'
import { Route as AuthenticatedXeriteRouteImport } from './routes/_authenticated/xerite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AstroloqRoute = AstroloqRouteImport.update({
  id: '/astroloq',
  path: '/astroloq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroskopRoute = HoroskopRouteImport.update({
  id: '/horoskop',
  path: '/horoskop',
  getParentRoute: () => rootRouteImport,
} as any)
const MetnuRoute = MetnuRouteImport.update({
  id: '/metnu',
  path: '/metnu',
  getParentRoute: () => rootRouteImport,
} as any)
const QezetRoute = QezetRouteImport.update({
  id: '/qezet',
  path: '/qezet',
  getParentRoute: () => rootRouteImport,
} as any)
const UygunluqRoute = UygunluqRouteImport.update({
  id: '/uygunluq',
  path: '/uygunluq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJurnalRoute = AuthenticatedJurnalRouteImport.update({
  id: '/jurnal',
  path: '/jurnal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRezervasiyalarRoute =
  AuthenticatedRezervasiyalarRouteImport.update({
    id: '/rezervasiyalar',
    path: '/rezervasiyalar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedXeriteRoute = AuthenticatedXeriteRouteImport.update({
  id: '/xerite',
  path: '/xerite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astroloq': typeof AstroloqRoute
  '/auth': typeof AuthRoute
  '/forum': typeof ForumRoute
  '/horoskop': typeof HoroskopRoute
  '/metnu': typeof MetnuRoute
  '/qezet': typeof QezetRoute
  '/uygunluq': typeof UygunluqRoute
  '/jurnal': typeof AuthenticatedJurnalRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rezervasiyalar': typeof AuthenticatedRezervasiyalarRoute
  '/xerite': typeof AuthenticatedXeriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astroloq': typeof AstroloqRoute
  '/auth': typeof AuthRoute
  '/forum': typeof ForumRoute
  '/horoskop': typeof HoroskopRoute
  '/metnu': typeof MetnuRoute
  '/qezet': typeof QezetRoute
  '/uygunluq': typeof UygunluqRoute
  '/jurnal': typeof AuthenticatedJurnalRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rezervasiyalar': typeof AuthenticatedRezervasiyalarRoute
  '/xerite': typeof AuthenticatedXeriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/astroloq': typeof AstroloqRoute
  '/auth': typeof AuthRoute
  '/forum': typeof ForumRoute
  '/horoskop': typeof HoroskopRoute
  '/metnu': typeof MetnuRoute
  '/qezet': typeof QezetRoute
  '/uygunluq': typeof UygunluqRoute
  '/_authenticated/jurnal': typeof AuthenticatedJurnalRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/rezervasiyalar': typeof AuthenticatedRezervasiyalarRoute
  '/_authenticated/xerite': typeof AuthenticatedXeriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/astroloq'
    | '/auth'
    | '/forum'
    | '/horoskop'
    | '/metnu'
    | '/qezet'
    | '/uygunluq'
    | '/jurnal'
    | '/profil'
    | '/rezervasiyalar'
    | '/xerite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/astroloq'
    | '/auth'
    | '/forum'
    | '/horoskop'
    | '/metnu'
    | '/qezet'
    | '/uygunluq'
    | '/jurnal'
    | '/profil'
    | '/rezervasiyalar'
    | '/xerite'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/astroloq'
    | '/auth'
    | '/forum'
    | '/horoskop'
    | '/metnu'
    | '/qezet'
    | '/uygunluq'
    | '/_authenticated/jurnal'
    | '/_authenticated/profil'
    | '/_authenticated/rezervasiyalar'
    | '/_authenticated/xerite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AstroloqRoute: typeof AstroloqRoute
  AuthRoute: typeof AuthRoute
  ForumRoute: typeof ForumRoute
  HoroskopRoute: typeof HoroskopRoute
  MetnuRoute: typeof MetnuRoute
  QezetRoute: typeof QezetRoute
  UygunluqRoute: typeof UygunluqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astroloq': {
      id: '/astroloq'
      path: '/astroloq'
      fullPath: '/astroloq'
      preLoaderRoute: typeof AstroloqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoskop': {
      id: '/horoskop'
      path: '/horoskop'
      fullPath: '/horoskop'
      preLoaderRoute: typeof HoroskopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metnu': {
      id: '/metnu'
      path: '/metnu'
      fullPath: '/metnu'
      preLoaderRoute: typeof MetnuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qezet': {
      id: '/qezet'
      path: '/qezet'
      fullPath: '/qezet'
      preLoaderRoute: typeof QezetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uygunluq': {
      id: '/uygunluq'
      path: '/uygunluq'
      fullPath: '/uygunluq'
      preLoaderRoute: typeof UygunluqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jurnal': {
      id: '/_authenticated/jurnal'
      path: '/jurnal'
      fullPath: '/jurnal'
      preLoaderRoute: typeof AuthenticatedJurnalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rezervasiyalar': {
      id: '/_authenticated/rezervasiyalar'
      path: '/rezervasiyalar'
      fullPath: '/rezervasiyalar'
      preLoaderRoute: typeof AuthenticatedRezervasiyalarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/xerite': {
      id: '/_authenticated/xerite'
      path: '/xerite'
      fullPath: '/xerite'
      preLoaderRoute: typeof AuthenticatedXeriteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedJurnalRoute: typeof AuthenticatedJurnalRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRezervasiyalarRoute: typeof AuthenticatedRezervasiyalarRoute
  AuthenticatedXeriteRoute: typeof AuthenticatedXeriteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedJurnalRoute: AuthenticatedJurnalRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRezervasiyalarRoute: AuthenticatedRezervasiyalarRoute,
  AuthenticatedXeriteRoute: AuthenticatedXeriteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AstroloqRoute: AstroloqRoute,
  AuthRoute: AuthRoute,
  ForumRoute: ForumRoute,
  HoroskopRoute: HoroskopRoute,
  MetnuRoute: MetnuRoute,
  QezetRoute: QezetRoute,
  UygunluqRoute: UygunluqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
