/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AstroloqRouteImport } from './routes/astroloq'
import { Route as HoroskopRouteImport } from './routes/horoskop'
import { Route as QezetRouteImport } from './routes/qezet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AstroloqRoute = AstroloqRouteImport.update({
  id: '/astroloq',
  path: '/astroloq',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroskopRoute = HoroskopRouteImport.update({
  id: '/horoskop',
  path: '/horoskop',
  getParentRoute: () => rootRouteImport,
} as any)
const QezetRoute = QezetRouteImport.update({
  id: '/qezet',
  path: '/qezet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astroloq': typeof AstroloqRoute
  '/horoskop': typeof HoroskopRoute
  '/qezet': typeof QezetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astroloq': typeof AstroloqRoute
  '/horoskop': typeof HoroskopRoute
  '/qezet': typeof QezetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/astroloq': typeof AstroloqRoute
  '/horoskop': typeof HoroskopRoute
  '/qezet': typeof QezetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/astroloq' | '/horoskop' | '/qezet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/astroloq' | '/horoskop' | '/qezet'
  id: '__root__' | '/' | '/astroloq' | '/horoskop' | '/qezet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AstroloqRoute: typeof AstroloqRoute
  HoroskopRoute: typeof HoroskopRoute
  QezetRoute: typeof QezetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astroloq': {
      id: '/astroloq'
      path: '/astroloq'
      fullPath: '/astroloq'
      preLoaderRoute: typeof AstroloqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoskop': {
      id: '/horoskop'
      path: '/horoskop'
      fullPath: '/horoskop'
      preLoaderRoute: typeof HoroskopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qezet': {
      id: '/qezet'
      path: '/qezet'
      fullPath: '/qezet'
      preLoaderRoute: typeof QezetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AstroloqRoute: AstroloqRoute,
  HoroskopRoute: HoroskopRoute,
  QezetRoute: QezetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
